### ISSUE TITLE
Problem list is not updated when problem is deleted.

### ISSUE THREAD

**Issue by VinnyLuu** [CMPUT301F18T07/TheIrisProject#107]
Similar to the issue we had with the adding of problems, the problem list is not updated after problem is deleted after returning from deleteproblemactivity. Will update if go and return from a different activity.

**Comment by anticobalt** [comment]
Related issue: if you click on the deleted Problem the app crashes. Will be resolved by resolving the update issue.

**Comment by anticobalt** [comment]
Fixed some time ago.
