### ISSUE TITLE
LoginTask getSourceAsObject issue

### ISSUE THREAD

**Issue by itstc** [CMPUT301F18T07/TheIrisProject#51]
Currently, I set the parameter for getSourceAsObject to be `Patient.class` but that is not always the case (logging in as care provider). There are 2 ways to fix this issue.
* Get response as JSON first, then check the type which is either "PATIENT" or "CAREPROVIDER" and create a class accordingly.

* Make User class instantiable such that we can convert it to a Patient/CareProvider Class later. This also has issues as we may lose information exclusive to Patient or CareProvider if the database is not structured correctly to address this.

**Comment by Jmmxp** [comment]
1) looks like the better solution but it might not actually be possible; we won't be able to getJsonObject if we're doing a match for email instead of term (and of course term isn't possible at the moment)
