### ISSUE TITLE
CareProvider's Patients List not being updated immediately after adding

### ISSUE THREAD

**Issue by Jmmxp** [CMPUT301F18T07/TheIrisProject#84]
If you log in as a Care Provider and add a Patient using their email, although it shows up on the ListView of Patients after you relog or go to a different screen, it doesn't render immediately after adding. I've tried to 

1) Change rendering to happen in onResume instead of onStart
2) use Callbacks to force it to render after every time a Patient is added

and none of these have worked.

**Comment by itstc** [comment]
This seems like a server-side issue as we are trying to query the patients with the care provider id in their careProviderIds, but has the added patients list of ids is not yet updated. I found that if you sleep the async thread by 500ms everything works fine (maybe not the best solution).

**Comment by Jmmxp** [comment]
Fixed
